// Add or edit content here before changing the game engine in app.js.
window.GAME_CONTENT = {
  technicians: [
    {
      // TODO: Migrate this save-compatible ID to "alex" when formal save migrations exist.
      id: "prototype-tech",
      name: "Alex",
      role: "Commercial Helper",
      tagline: "New to the trade. One screwdriver. No onboarding packet.",
      description: "Alex is starting out as a commercial AV helper at a badly managed shop. They do not have Wiley's residential install instincts, a programmer's systems knowledge, or a senior tech's judgment yet. What they do have is a willingness to learn, follow direction, and build good habits before the industry teaches them bad ones.",
      strengths: ["Balanced growth", "No major starting penalty", "Good first-play learning character", "Can develop into any role"],
      weaknesses: ["No strong specialty", "Limited starting tools", "Fewer unique shortcuts", "Needs training and gear to become distinct"],
      playstyle: "Balanced starter for new players who want to learn the commercial AV loop from the ground up.",
      difficulty: "Easy",
      trait: "Clean Slate",
      tendency: "Ask, learn, then do it twice because the first instruction was incomplete",
      stats: { energy: 100, burnout: 0, craftsmanship: 2, confidence: 1 },
      characterStats: {
        install: 2,
        troubleshooting: 2,
        documentation: 2,
        clientCommunication: 2,
        fieldcraft: 2,
        commercialProcess: 2,
        networking: 1,
        dspAudio: 1,
        controlSystems: 1,
        toolPreparedness: 1,
        improvisation: 1,
        burnoutResistance: 2,
      },
      traits: ["balancedStarter", "calmUnderFire"],
      startingTools: ["screwdriver"],
    },
    {
      id: "organized-rookie",
      name: "Casey",
      role: "Shop-Organized Apprentice",
      tagline: "Brought a tool bag, snacks, and a dangerous belief in written notes.",
      description: "Casey came up through staging, warehouse runs, and helping the organized techs who somehow know where the spare Phoenix connectors live. They are not the fastest installer, but their notes survive contact with Monday morning.",
      strengths: ["Documentation", "Field readiness", "Careful prep", "Low-drama closeout"],
      weaknesses: ["Client confidence", "Fast improvisation", "Big physical installs"],
      playstyle: "Careful planner who spends a little time upfront to make later work less ridiculous.",
      difficulty: "Easy",
      trait: "Notebook Habit",
      tendency: "Measure Twice",
      stats: { energy: 105, burnout: 0, craftsmanship: 2, confidence: 0 },
      characterStats: {
        install: 2,
        troubleshooting: 2,
        documentation: 3,
        clientCommunication: 1,
        fieldcraft: 3,
        commercialProcess: 3,
        networking: 1,
        dspAudio: 1,
        controlSystems: 1,
        toolPreparedness: 3,
        improvisation: 1,
        burnoutResistance: 3,
      },
      traits: ["measureTwice", "notebookHabit"],
      startingTools: ["screwdriver", "toolBag"],
    },
    {
      id: "wiley",
      name: "Wiley",
      role: "Residential Install Tech",
      tagline: "Former Circuit Hut counter guy. Fast with tools, new to commercial process.",
      description: "Wiley spent years mounting TVs, fishing wires, cleaning up racks, tracing mystery speaker lines, replacing remotes, and making bad homeowner purchases work just well enough to survive the day.",
      strengths: ["Physical install", "Retrofit paths", "Small parts", "Practical troubleshooting"],
      weaknesses: ["Commercial process", "Documentation", "DSP/control", "Networking"],
      playstyle: "Fast hands-on installer with strong improvisation, but must learn commercial process.",
      difficulty: "Medium",
      trait: "Circuit Hut Parts Brain",
      tendency: "I Can Make That Work",
      stats: { energy: 105, burnout: 0, craftsmanship: 3, confidence: 0 },
      characterStats: {
        install: 5,
        toolPreparedness: 5,
        improvisation: 5,
        residentialKnowledge: 5,
        practicalTroubleshooting: 4,
        troubleshooting: 4,
        clientCommunication: 3,
        commercialProcess: 1,
        documentation: 1,
        fieldcraft: 5,
        dspAudio: 1,
        controlSystems: 1,
        networking: 1,
        burnoutResistance: 3,
      },
      traits: ["circuitHutPartsBrain", "makeThatWork", "residentialInstinct"],
      startingTools: ["screwdriver", "toolBag", "circuitHutOrganizer"],
    },
    {
      id: "jordan",
      name: "Jordan",
      role: "Helpdesk Convert",
      tagline: "Ticket brain. Clean notes. Still learning which wall dust is expensive.",
      description: "Jordan learned AV from support tickets, screenshots, and the cold realization that 'it worked yesterday' is not a diagnosis. They are great at tracing symptoms and writing useful notes, but heavy install days can expose the gap between knowing the system and landing it neatly.",
      strengths: ["Troubleshooting", "Documentation", "Commercial process", "Client explanations"],
      weaknesses: ["Physical install speed", "Improvisation", "Long carries", "Tool depth"],
      playstyle: "Methodical service tech who can prevent callbacks by proving the signal path before touching hardware.",
      difficulty: "Medium",
      trait: "By The Book",
      tendency: "Ticket First, Then Touch It",
      stats: { energy: 95, burnout: 0, craftsmanship: 1, confidence: 2 },
      characterStats: {
        install: 1,
        troubleshooting: 5,
        documentation: 4,
        clientCommunication: 3,
        fieldcraft: 2,
        commercialProcess: 4,
        networking: 4,
        controlSystems: 2,
        dspAudio: 2,
        improvisation: 1,
        burnoutResistance: 2,
      },
      traits: ["byTheBook", "notebookHabit", "knowsAGuy"],
      startingTools: ["screwdriver"],
    },
    {
      id: "morgan",
      name: "Morgan",
      role: "Live Events Tech",
      tagline: "Can talk through a room panic. Owns too much black gaff tape.",
      description: "Morgan came from shows, ballrooms, and last-minute executive microphones. They are strong when clients are staring and the room has to work right now, but commercial documentation feels slower than a keynote rehearsal with no run sheet.",
      strengths: ["Client communication", "Pressure handling", "Fieldcraft", "Fast troubleshooting"],
      weaknesses: ["Documentation", "Formal closeout", "Commercial process", "Burnout risk"],
      playstyle: "Social pressure-handler who unlocks calmer pushback and handoff paths earlier than most rookies.",
      difficulty: "Medium",
      trait: "Calm Under Fire",
      tendency: "Show Must Go On, But Please Label It Later",
      stats: { energy: 100, burnout: 1, craftsmanship: 2, confidence: 3 },
      characterStats: {
        install: 2,
        troubleshooting: 3,
        documentation: 1,
        clientCommunication: 5,
        fieldcraft: 4,
        commercialProcess: 1,
        networking: 1,
        dspAudio: 2,
        controlSystems: 1,
        improvisation: 3,
        liveEvents: 5,
        toolPreparedness: 2,
        burnoutResistance: 2,
      },
      traits: ["calmUnderFire", "knowsAGuy", "steadyHands"],
      startingTools: ["screwdriver", "toolBag"],
    },
  ],

  currentCompanyId: "radnor-rack-wire",

  companies: {
    "radnor-rack-wire": {
      id: "radnor-rack-wire",
      name: "Radnor Rack & Wire",
      role: "Starter Employer",
      culture: "Badly managed regional AV shop",
      homeBase: "Wayne Area, PA",
      summary: "A disorganized commercial AV shop where capable field people keep rescuing schedules that were never realistic.",
      strengths: ["Enough work to learn fast", "Josh still answers questions", "Sometimes the spare part actually exists"],
      dysfunctions: ["Optimistic estimates", "Weak dispatch notes", "Delayed reimbursement", "Management blames the person fixing the issue"],
      reputationPressure: "Management likes clean tickets. Clients and coworkers like honest closeout.",
      pressureRules: [
        {
          id: "clean-ticket-pressure",
          name: "Clean Ticket Pressure",
          trigger: "Fast closeouts and short notes make management happier.",
          fieldReality: "Client and coworker trust often require writing the problem down before it becomes a return trip.",
        },
        {
          id: "scope-denial",
          name: "Scope Denial",
          trigger: "Anything not in the quote gets treated like a personal hobby.",
          fieldReality: "Documenting the mismatch protects the next tech and may create management friction.",
        },
        {
          id: "reimbursement-friction",
          name: "Reimbursement Friction",
          trigger: "Parking, tolls, and small supplies are always somehow your paperwork problem.",
          fieldReality: "Prep choices and tools reduce pain, but the company still calls it efficiency.",
        },
      ],
      expansionUse: "Keep this as the first-company baseline. Future companies can change shop culture, supplied tools, dispatch expectations, and reputation pressure without changing technician data.",
    },
  },

  jobFamilies: {
    install: {
      id: "install",
      name: "Install",
      coreSkills: ["install", "fieldcraft", "documentation"],
      loop: "Load, carry, assemble, verify, close out.",
      commonChoices: ["Clean finish vs. leave on time", "Tool prep vs. extra energy cost", "Document issue vs. keep ticket simple"],
      expansionUse: "Use for mounting, carts, racks, rooms, and physical buildouts.",
    },
    service: {
      id: "service",
      name: "Service",
      coreSkills: ["troubleshooting", "documentation", "clientCommunication"],
      loop: "Read history, inspect symptoms, verify signal path, choose speed or root cause.",
      commonChoices: ["Trust ticket vs. diagnose", "Patch vs. fix", "Tell client tradeoff vs. keep management happy"],
      expansionUse: "Use for flicker, audio dropouts, control weirdness, remote support follow-ups, and warranty calls.",
    },
    survey: {
      id: "survey",
      name: "Site Survey",
      coreSkills: ["documentation", "clientCommunication", "fieldcraft"],
      loop: "Inspect constraints, compare against quote, write the problem before install day.",
      commonChoices: ["Document risk vs. trust sales", "Push back calmly vs. avoid friction", "Measure path vs. assume access"],
      expansionUse: "Use when the job is mostly observation, access, scope, and protecting the future crew.",
    },
    commissioning: {
      id: "commissioning",
      name: "Commissioning",
      coreSkills: ["troubleshooting", "install", "documentation"],
      loop: "Test the room, find incomplete work, choose the closeout standard.",
      commonChoices: ["Pass room vs. punch list", "Repair cleanly vs. document mismatch", "Protect client trust vs. protect schedule"],
      expansionUse: "Use for DSP tuning, control checks, source routing, punch lists, and rooms closed too early.",
    },
    logistics: {
      id: "logistics",
      name: "Logistics",
      coreSkills: ["fieldcraft", "documentation", "clientCommunication"],
      loop: "Find, stage, move, label, or route around missing prep.",
      commonChoices: ["Fix stock issue vs. hand off fast", "Eat access delay vs. document it", "Use company process vs. field workaround"],
      expansionUse: "Use for warehouse runs, access jobs, vehicle prep, travel complications, and supply-counter friction.",
    },
    handoff: {
      id: "handoff",
      name: "Client Handoff",
      coreSkills: ["clientCommunication", "documentation", "troubleshooting"],
      loop: "Learn what the client actually needs, translate the system, and leave usable instructions.",
      commonChoices: ["Patient walkthrough vs. quick demo", "Client-language notes vs. button-label notes", "Answer questions vs. protect schedule"],
      expansionUse: "Use for training, turnover, executive rooms, facility staff coaching, and nontechnical success conditions.",
    },
  },

  traitContextBonuses: {
    notebookHabit: [
      { skillId: "documentation", contextIds: ["survey-documentation", "secure-access-documentation", "callback-documentation", "handoff-documentation", "commissioning-documentation"], bonus: 1 },
    ],
    byTheBook: [
      { skillId: "documentation", contextIds: ["survey-documentation", "secure-access-documentation", "callback-documentation", "handoff-documentation", "commissioning-documentation"], bonus: 1 },
      { skillId: "troubleshooting", contextIds: ["service-diagnosis", "commissioning-troubleshooting", "callback-troubleshooting"], bonus: 1 },
    ],
    calmUnderFire: [
      { skillId: "clientCommunication", contextIds: ["survey-pressure", "secure-access-pressure", "handoff-pressure", "commissioning-pressure"], bonus: 1 },
    ],
    knowsAGuy: [
      { skillId: "clientCommunication", contextIds: ["survey-pressure", "secure-access-pressure", "handoff-pressure", "commissioning-pressure"], bonus: 1 },
    ],
    steadyHands: [
      { skillId: "install", contextIds: ["cart-assembly", "service-install", "commissioning-termination"], bonus: 1 },
    ],
  },

  characterCreation: {
    designStatus: "first-release",
    summary: "Custom characters combine a work background, a work style, two traits, and major skill picks. Premade technicians are templates built from the same ingredients.",
    baseStats: { energy: 100, burnout: 0, craftsmanship: 2, confidence: 1 },
    baseSkills: {
      install: 1,
      troubleshooting: 1,
      documentation: 1,
      clientCommunication: 1,
      fieldcraft: 1,
      commercialProcess: 1,
      networking: 1,
      dspAudio: 1,
      controlSystems: 1,
    },
    primarySkillBonus: 2,
    secondarySkillBonus: 1,
    traitSlots: 2,
    backgrounds: [
      {
        id: "residential-installer",
        name: "Residential Installer",
        role: "Retrofit-heavy hands-on tech",
        skillBonuses: { install: 2, troubleshooting: 1, fieldcraft: 1 },
        characterStats: { improvisation: 2, residentialKnowledge: 3 },
        statModifiers: { craftsmanship: 1, confidence: -1 },
        traits: ["residentialInstinct"],
        startingTools: ["toolBag"],
        tradeoff: "Strong with physical work and improvised paths, weaker at commercial documentation.",
      },
      {
        id: "warehouse-runner",
        name: "Warehouse Runner",
        role: "Shop logistics and staging helper",
        skillBonuses: { fieldcraft: 2, documentation: 1 },
        statModifiers: { energy: 5 },
        startingTools: ["toolBag"],
        tradeoff: "Better at prep and carrying, less confident during client-facing decisions.",
      },
      {
        id: "helpdesk-convert",
        name: "Helpdesk Convert",
        role: "Ticket-driven troubleshooter",
        skillBonuses: { troubleshooting: 2, documentation: 1, clientCommunication: 1 },
        statModifiers: { craftsmanship: -1 },
        startingTools: [],
        tradeoff: "Good diagnostic habits, weaker physical install baseline.",
      },
      {
        id: "live-events-tech",
        name: "Live Events Tech",
        role: "Show-must-go-on operator",
        skillBonuses: { clientCommunication: 2, fieldcraft: 1, troubleshooting: 1 },
        statModifiers: { confidence: 1, burnout: 1 },
        startingTools: [],
        tradeoff: "Calm under pressure, but more vulnerable to burnout when jobs run long.",
      },
      {
        id: "green-apprentice",
        name: "Green Apprentice",
        role: "New helper with fewer bad habits",
        skillBonuses: { install: 1, documentation: 1, fieldcraft: 1 },
        statModifiers: { energy: 5 },
        startingTools: [],
        tradeoff: "Balanced and teachable, but starts without a strong specialty.",
      },
    ],
    workStyles: [
      {
        id: "measure-twice",
        name: "Measure Twice",
        effect: "Careful task choices get stronger payoff and callback risk drops.",
        skillBonuses: { documentation: 1 },
        traits: ["measureTwice"],
        tradeoff: "Rushed work costs more energy because this tech fights their own habits.",
      },
      {
        id: "make-it-work",
        name: "Make It Work",
        effect: "Unlocks practical workaround choices and small-parts improvisation.",
        skillBonuses: { install: 1, troubleshooting: 1 },
        characterStats: { improvisation: 4 },
        traits: ["makeThatWork"],
        tradeoff: "Temporary fixes create more callback debt unless documented cleanly.",
      },
      {
        id: "calm-under-fire",
        name: "Calm Under Fire",
        effect: "Pressure checks with clients, supervisors, and access desks are easier.",
        skillBonuses: { clientCommunication: 1 },
        traits: ["calmUnderFire"],
        tradeoff: "Lower early hands-on bonus than a specialist background.",
      },
      {
        id: "parts-brain",
        name: "Parts Brain",
        effect: "Can search a personal organizer once per dispatch for a testing aid.",
        skillBonuses: { fieldcraft: 1 },
        traits: ["circuitHutPartsBrain"],
        startingTools: ["circuitHutOrganizer"],
        tradeoff: "Testing shortcuts still need proper closeout or they become future risk.",
      },
      {
        id: "by-the-book",
        name: "By The Book",
        effect: "Documentation and management-protection choices become more reliable.",
        skillBonuses: { documentation: 1, clientCommunication: 1 },
        traits: ["byTheBook"],
        tradeoff: "Overusing process can cost coworker trust on messy jobs.",
      },
    ],
    traits: [
      {
        id: "steady-hands",
        name: "Steady Hands",
        effect: "+1 to cable termination and re-termination checks.",
        skillBonuses: { install: 1 },
        traits: ["steadyHands"],
        tradeoff: "No social or paperwork benefit.",
      },
      {
        id: "notebook-habit",
        name: "Notebook Habit",
        effect: "+1 Documentation during surveys and access problems.",
        skillBonuses: { documentation: 1 },
        traits: ["notebookHabit"],
        tradeoff: "No speed benefit when the job is already late.",
      },
      {
        id: "tool-debt",
        name: "Tool Debt",
        effect: "Start with one extra stocked personal tool.",
        startingTools: ["drill"],
        cashModifier: -75,
        traits: ["toolDebt"],
        tradeoff: "Start with less cash.",
      },
      {
        id: "knows-a-guy",
        name: "Knows A Guy",
        effect: "Coworker and vendor conversations can open extra options.",
        skillBonuses: { clientCommunication: 1 },
        traits: ["knowsAGuy"],
        tradeoff: "Management reputation gains are smaller when favors bypass process.",
      },
      {
        id: "bad-knees",
        name: "Bad Knees",
        effect: "+1 Documentation from planning around access and lifts.",
        skillBonuses: { documentation: 1 },
        statModifiers: { energy: -10 },
        traits: ["badKnees"],
        tradeoff: "Stairs, long carries, and repeated garage trips cost more energy.",
      },
    ],
    premadeTemplates: [
      {
        technicianId: "wiley",
        formula: "Residential Installer + Parts Brain + Make It Work",
      },
      {
        technicianId: "organized-rookie",
        formula: "Warehouse Runner + Measure Twice + Notebook Habit",
      },
      {
        technicianId: "prototype-tech",
        formula: "Green Apprentice + Calm Under Fire",
      },
      {
        technicianId: "jordan",
        formula: "Helpdesk Convert + By The Book + Notebook Habit + Knows A Guy",
      },
      {
        technicianId: "morgan",
        formula: "Live Events Tech + Calm Under Fire + Knows A Guy + Steady Hands",
      },
    ],
  },

  characterLines: {
    wiley: {
      accessoryTote: 'Wiley clocked the accessory tote first. "Adapters are where simple jobs go to negotiate."',
      inspectVan: 'Wiley checks the van bins. "I found three cables we do not need and zero of the one we do. Classic."',
      finishChoice: "Wiley can make the awkward adapter path work for now. The question is whether it deserves to become the install.",
      workaroundLog: "Wiley made the adapter path work for now. The closeout notes did not get smarter.",
      partsBrainQuote: "I can make it work. I'm just asking whether we want it to keep working.",
      serviceInspect: 'Wiley eyes the coupler behind the credenza. "I trust this adapter for testing. I do not trust it with my reputation."',
      surveyWall: 'Wiley checks the wall like someone who has met plaster before. "Before we drill, let us find out if this wall is drywall, brick, or a lawsuit."',
    },
  },

  tools: {
    screwdriver: {
      id: "screwdriver",
      name: "Basic Screwdriver",
      description: "The one tool you knew to bring.",
      effect: "Allows basic assembly.",
      price: 0,
    },
    toolBag: {
      id: "toolBag",
      name: "Tool Bag",
      description: "A place for your tools that is not a cardboard box.",
      effect: "Reduce energy spent picking up equipment by 1.",
      modifiers: { pickupEnergyReduction: 1 },
      skillBonuses: { fieldcraft: 1 },
      price: 65,
    },
    drill: {
      id: "drill",
      name: "Basic Drill",
      description: "Entry-level, but the battery is yours.",
      effect: "Reduce energy spent assembling equipment by 4.",
      modifiers: { assemblyEnergyReduction: 4 },
      skillBonuses: { install: 1 },
      price: 125,
    },
    handTruck: {
      id: "handTruck",
      name: "Folding Hand Truck",
      description: "Carry more gear before your next garage trip.",
      effect: "Carry one additional equipment group during garage unloads.",
      modifiers: { garageCarryCapacityBonus: 1 },
      skillBonuses: { fieldcraft: 1 },
      price: 100,
    },
    labeler: {
      id: "labeler",
      name: "Josh's Rebuilt Labeler",
      description: "Josh repaired the feed roller and wrote your name inside the battery cover.",
      effect: "Reduce energy spent verifying signal paths by 2.",
      modifiers: { verificationEnergyReduction: 2 },
      skillBonuses: { documentation: 1 },
      price: 0,
    },
    circuitHutOrganizer: {
      id: "circuitHutOrganizer",
      name: "Circuit Hut Parts Organizer",
      description: "A battered small-parts case from Wiley's counter days. It contains useful adapters, odd connectors, and several things that should never become permanent.",
      effect: "Once per dispatch, search for a small testing part. If used, reduce verification and testing energy by 1 for that dispatch.",
      modifiers: { partsBrainVerificationReduction: 1 },
      finds: [
        "right-angle HDMI adapter",
        "HDMI coupler",
        "Phoenix connector with one suspicious screw",
        "short patch cable",
        "keystone coupler",
        "IR emitter",
        "fresh batteries",
        "label scraps",
      ],
      price: 0,
    },
  },

  vehicles: {
    van3: {
      id: "van3",
      name: "Company Van #3",
      cargoCapacity: 3,
      organization: "Poor",
      reliability: "Questionable",
      fuelEconomy: "Not discussed",
      clearance: "Garage-sized, probably",
      comfort: "The passenger window mostly closes.",
    },
  },

  career: {
    ranks: [
      { level: 1, name: "Helper", xpRequired: 0 },
      { level: 2, name: "Junior Tech", xpRequired: 80 },
      { level: 3, name: "Field Tech", xpRequired: 180 },
    ],
    goals: [
      {
        id: "junior-tech",
        name: "Become Junior Tech",
        metric: "xp",
        target: 80,
        reward: "First field-training focus unlocks.",
      },
      {
        id: "field-tech",
        name: "Become Field Tech",
        metric: "xp",
        target: 180,
        reward: "Certification choices can branch from this rank later.",
      },
      {
        id: "crew-trust",
        name: "Earn Crew Trust",
        metric: "coworkerReputation",
        target: 2,
        reward: "Coworker tools and stronger handoffs unlock.",
      },
      {
        id: "careful-rhythm",
        name: "Build Careful-Work Rhythm",
        metric: "carefulFinishes",
        target: 2,
        reward: "Repair and punch-list work costs 1 less energy.",
      },
      {
        id: "documentation-habit",
        name: "Build Documentation Habit",
        metric: "documentedRisks",
        target: 2,
        reward: "Report and access-delay paperwork costs 1 less energy.",
      },
      {
        id: "personal-kit",
        name: "Build Personal Kit",
        metric: "ownedPaidTools",
        target: 3,
        reward: "More future job options can key off owned tools.",
      },
      {
        id: "field-task-habit",
        name: "Make Field Task Choices",
        metric: "fieldTaskChoicesMade",
        target: 3,
        reward: "Future jobs can branch around task-quality history.",
      },
    ],
    skills: [
      {
        id: "install",
        name: "Install",
        branch: "Hands-On",
        description: "Mounting, dressing, landing, and terminating physical work so it survives real use.",
      },
      {
        id: "troubleshooting",
        name: "Troubleshooting",
        branch: "Signal Path",
        description: "Tracing faults before replacing parts or writing an overconfident closeout note.",
      },
      {
        id: "documentation",
        name: "Documentation",
        branch: "Process",
        description: "Leaving notes, labels, and survey details the next person can actually trust.",
      },
      {
        id: "clientCommunication",
        name: "Client Communication",
        branch: "People",
        description: "Explaining tradeoffs clearly when the room, client, and schedule disagree.",
      },
      {
        id: "fieldcraft",
        name: "Fieldcraft",
        branch: "Readiness",
        description: "Preparation, tool discipline, and the practical habits that make messy jobs cheaper.",
      },
      {
        id: "commercialProcess",
        name: "Commercial Process",
        branch: "Process",
        description: "Reading scope, access rules, closeout expectations, and the paperwork traps around the work.",
      },
      {
        id: "networking",
        name: "Networking",
        branch: "Systems",
        description: "IP addresses, switch ports, discovery problems, and the moment a room becomes an IT conversation.",
      },
      {
        id: "dspAudio",
        name: "DSP / Audio",
        branch: "Systems",
        description: "Gain structure, signal routing, mute logic, AEC, and why one ceiling speaker chose silence.",
      },
      {
        id: "controlSystems",
        name: "Control Systems",
        branch: "Systems",
        description: "Touch panels, button logic, source routing, room presets, and user paths that need to make sense.",
      },
    ],
    trainingChoices: [
      {
        id: "craftsmanship",
        name: "Neater Installs",
        description: "Practice cable dressing, labeling, and the quiet art of leaving a room better than you found it.",
        branch: "Hands-On",
        effect: "+1 Craftsmanship, +1 Install, +1 Documentation",
        modifiers: { craftsmanship: 1 },
        skillBonuses: { install: 1, documentation: 1 },
      },
      {
        id: "confidence",
        name: "Calm Troubleshooting",
        description: "Build a repeatable process for the moment when everyone else starts guessing.",
        branch: "Signal Path",
        effect: "+1 Confidence, +1 Troubleshooting, +1 Client Communication",
        modifiers: { confidence: 1 },
        skillBonuses: { troubleshooting: 1, clientCommunication: 1 },
      },
      {
        id: "endurance",
        name: "Pack A Lunch",
        description: "A small amount of planning makes the long days less punishing.",
        branch: "Readiness",
        effect: "+10 maximum energy, +1 Fieldcraft",
        modifiers: { maxEnergy: 10 },
        skillBonuses: { fieldcraft: 1 },
      },
      {
        id: "systems-basics",
        name: "Systems Fundamentals",
        description: "Learn enough signal flow, network basics, and control-room vocabulary to ask better questions before swapping parts.",
        branch: "Systems",
        effect: "+1 Networking, +1 DSP / Audio, +1 Control Systems",
        modifiers: {},
        skillBonuses: { networking: 1, dspAudio: 1, controlSystems: 1 },
      },
    ],
  },

  coworkers: {
    josh: {
      id: "josh",
      name: "Josh",
      role: "Lead Technician",
      description: "Patient, capable, and somehow blamed whenever the schedule meets reality.",
      labelerTrustRequired: 2,
    },
  },

  tutorial: {
    shopLoad: ["Cart frame boxes", "Display boxes", "Accessory tote"],
    garageUnload: ["Cart frame boxes", "Display boxes", "Accessory tote"],
    assembly: [
      { id: "cart-1-frame", label: "Cart 1 frame", destination: "cart1" },
      { id: "cart-1-display", label: "Cart 1 display", destination: "cart1" },
      { id: "cart-2-frame", label: "Cart 2 frame", destination: "cart2" },
      { id: "cart-2-display", label: "Cart 2 display", destination: "cart2" },
    ],
    rewardTools: ["toolBag", "drill", "handTruck"],
  },

  serviceDispatch: {
    title: "One Quick Display Swap",
    summary: "Replace a conference-room display at a Conshohocken office.",
    swapItems: [
      { id: "replacement-display", label: "Replacement display" },
      { id: "mount-hardware", label: "Mount hardware tote" },
    ],
  },

  surveyDispatch: {
    title: "University City Site Survey",
    summary: "Confirm whether a quoted classroom display can reach its intended wall.",
    inspections: [
      {
        id: "elevator",
        label: "Freight elevator opening",
        log: "the proposed display carton is wider than the clear opening",
        detail: "The freight elevator is functional and reasonably clean. Its clear opening is narrower than the unopened 98-inch display carton shown on the sales sketch.",
      },
      {
        id: "hallway",
        label: "Hallway turn",
        log: "the corner removes the optimistic diagonal approach",
        detail: "The hallway makes a tight turn immediately after the elevator. Angling the carton might have been a theory in a larger hallway. This is not that hallway.",
      },
      {
        id: "wall",
        label: "Classroom display wall",
        log: "the wall works, which is how the access problem escaped the quote",
        detail: "The intended wall has enough space and nearby power. Sales measured this part correctly, then apparently stopped walking.",
      },
    ],
  },

  commissioningDispatch: {
    title: "South Philadelphia Commissioning",
    summary: "Commission a training room that is more complete on paper than in person.",
    taskCards: [
      {
        title: "Speaker Zone Test",
        skill: "Troubleshooting 3",
        outcome: "Confirms whether the quiet side is a real fault or a tuning complaint.",
      },
      {
        title: "Credenza Termination",
        skill: "Install 4",
        outcome: "Unlocks the re-land, re-terminate, and labeler task paths.",
      },
      {
        title: "Closeout Drawing",
        skill: "Documentation 3",
        outcome: "Decides whether the next tech gets usable notes or a mystery.",
      },
    ],
    checks: [
      {
        id: "speaker-zone",
        label: "Ceiling speaker zone",
        log: "the third speaker remains silent during the test tone",
        detail: "The first two ceiling speakers play the test tone. The third contributes a thoughtful silence from the back of the room.",
      },
      {
        id: "termination",
        label: "Credenza termination",
        log: "the silent speaker line is loose at the output block",
        detail: "The third speaker line is landed loosely at the output block. It is close enough to the terminal to suggest optimism, but not close enough to carry audio.",
      },
      {
        id: "drawing",
        label: "Closeout drawing",
        log: "the drawing belongs to the mirrored room across the hall",
        detail: "The closeout drawing is neat, legible, and for the mirrored room across the hall. Somebody changed the room number in the filename and declared victory.",
      },
    ],
  },

  warehouseDispatch: {
    title: "Warehouse Run",
    summary: "Find a replacement power supply reportedly stored in one of the vans.",
    checks: [
      {
        id: "staging",
        label: "Staging shelf",
        log: "the shelf contains the loaner-drill charger and several remotes for unknown displays",
        detail: "The staging shelf has the missing charger for the shop loaner drill, three remotes for displays the company does not own, and no matching power supply.",
      },
      {
        id: "van3",
        label: "Van #3",
        log: "the van crate contains power supplies for two different models and one empty tester case",
        detail: "Van #3 has a milk crate labeled MISC. Inside are two power supplies for the wrong display family and a cable-tester case containing no cable tester.",
      },
      {
        id: "returns",
        label: "Mystery-return pile",
        log: "the matching power supply is beneath a box labeled HDMI EXTENDERS / DO NOT STOCK / RETURN?",
        detail: "The correct power supply is in the mystery-return pile beneath a box labeled HDMI EXTENDERS / DO NOT STOCK / RETURN? The question mark appears to be the current inventory process.",
      },
    ],
  },

  secureAccessDispatch: {
    title: "Navy Yard Secure Access",
    summary: "Deliver a small rack update to a secure building after dispatch sends the wrong access note.",
    checks: [
      {
        id: "gate",
        label: "Security gate",
        log: "the guard has the company name but not today's visitor list",
        detail: "The guard recognizes the company because Josh was here last month, which is not the same as having your name on today's visitor list.",
      },
      {
        id: "building",
        label: "Building number",
        log: "the dispatch ticket and the security booth disagree by one building",
        detail: "Dispatch wrote Building 12. Security says the work order is for Building 13. The buildings are close enough to be annoying and far enough to matter.",
      },
      {
        id: "escort",
        label: "Escort requirement",
        log: "the telecom room requires an escort who is currently in another meeting",
        detail: "The telecom room is behind a badge reader and a policy nobody attached to the ticket. The escort is available after a meeting labeled 'quick sync.'",
      },
    ],
  },

  callbackCleanupDispatch: {
    title: "Warranty Return",
    summary: "Revisit a room that was marked complete before the callback ledger agreed.",
    checks: [
      {
        id: "client-notes",
        label: "Client complaint notes",
        log: "the complaint says intermittent, which is a word tickets use when they want company",
        detail: "The client reported that the issue comes back whenever the room is actually used. The ticket summary says 'user error?' with the question mark doing a lot of legal work.",
      },
      {
        id: "ticket-history",
        label: "Ticket history",
        log: "the previous closeout note is technically short enough to fit on a receipt",
        detail: "The closeout note says 'tested good.' It does not say what was tested, how long it was tested, or why the client immediately reopened the ticket.",
      },
      {
        id: "actual-fault",
        label: "Actual fault",
        log: "the original issue is still present behind a very confident status update",
        detail: "The fault is not exotic. It is a loose path, a bad assumption, and a room that got called complete before the boring verification happened.",
      },
    ],
  },

  handoffDispatch: {
    title: "Executive Handoff",
    summary: "Teach a client how to use a room that technically works but explains itself poorly.",
    checks: [
      {
        id: "control-panel",
        label: "Control panel labels",
        log: "the panel labels are technically words, just not the client's words",
        detail: "The panel has buttons named PRESENT, PC, SHARE, and AUX. The client asks which one starts the meeting. This is the correct question.",
      },
      {
        id: "daily-use",
        label: "Daily user path",
        log: "the common path is three steps if you already know the secret fourth step",
        detail: "Starting a normal meeting requires display power, laptop input, room audio, and the mute state nobody notices until the first sentence disappears.",
      },
      {
        id: "client-need",
        label: "Client's actual need",
        log: "the executive assistant needs repeatability more than feature coverage",
        detail: "The client does not need a tour of every input. They need the same morning meeting to work every time without texting facilities.",
      },
    ],
  },

  upcomingDispatches: [
    {
      title: "Cherry Hill Return Toll",
      summary: "Dispatch accounted for the bridge on the way there.",
    },
  ],

  scenes: {
    shop: {
      name: "Trunkslammer Shop",
      kicker: "Wayne Area, PA",
      playerStart: { x: 120, y: 430 },
      decor: [
        { type: "label", x: 44, y: 36, w: 220, h: 38, text: "RADNOR RACK & WIRE / UNIT 4" },
        { type: "office", x: 58, y: 110, w: 170, h: 140, text: "SALES OFFICE", solid: true },
        { type: "shelf", x: 480, y: 88, w: 220, h: 92, text: "STAGING AREA", solid: true },
        { type: "shelf", x: 500, y: 355, w: 160, h: 92, text: "MYSTERY RETURNS", solid: true },
        { type: "workbench", x: 270, y: 420, w: 170, h: 60, text: "TOOL WORKBENCH", solid: true },
        { type: "counter", x: 68, y: 300, w: 150, h: 64, text: "SUPPLY COUNTER", solid: true },
        { type: "break-area", x: 285, y: 95, w: 130, h: 70, text: "BREAK AREA", solid: true },
        { type: "van", x: 760, y: 280, w: 150, h: 190, text: "VAN #3", solid: true },
        { type: "floor-note", x: 278, y: 208, w: 150, h: 30, text: "UNLABELED CABLES" },
        { type: "floor-note", x: 432, y: 246, w: 150, h: 30, text: "CAREER CLIPBOARD" },
      ],
    },
    garage: {
      name: "Parking Garage",
      kicker: "Center City East",
      playerStart: { x: 650, y: 430 },
      decor: [
        { type: "label", x: 45, y: 36, w: 230, h: 38, text: "LEVEL B2 / SECTION C" },
        { type: "exit", x: 44, y: 115, w: 145, h: 110, text: "STREET EXIT", solid: true },
        { type: "van", x: 715, y: 260, w: 170, h: 210, text: "VAN #3", solid: true },
        { type: "floor-note", x: 330, y: 280, w: 210, h: 34, text: "A LONGER WALK THAN QUOTED" },
      ],
    },
    lobby: {
      name: "Client Lobby",
      kicker: "Center City East",
      playerStart: { x: 130, y: 420 },
      decor: [
        { type: "label", x: 45, y: 36, w: 210, h: 38, text: "CLIENT LOBBY" },
        { type: "desk", x: 295, y: 145, w: 220, h: 96, text: "SECURITY DESK", solid: true },
        { type: "elevator", x: 720, y: 95, w: 150, h: 190, text: "ELEVATORS", solid: true },
        { type: "floor-note", x: 232, y: 360, w: 270, h: 32, text: "VISITOR BADGE REQUIRED" },
      ],
    },
    client: {
      name: "Conference Room",
      kicker: "Center City East / Client Floor",
      playerStart: { x: 120, y: 430 },
      decor: [
        { type: "label", x: 45, y: 36, w: 220, h: 38, text: "TEMPORARY WORK AREA" },
        { type: "boxes", x: 90, y: 265, w: 175, h: 120, text: "DELIVERED BOXES", solid: true },
        { type: "build", x: 455, y: 120, w: 150, h: 150, text: "CART 1", solid: true },
        { type: "build", x: 680, y: 290, w: 150, h: 150, text: "CART 2", solid: true },
        { type: "floor-note", x: 345, y: 410, w: 210, h: 30, text: "PACKAGING ACCUMULATES HERE" },
      ],
    },
    serviceOffice: {
      name: "Conference Room 2B",
      kicker: "Conshohocken, PA",
      playerStart: { x: 120, y: 430 },
      decor: [
        { type: "label", x: 45, y: 36, w: 250, h: 38, text: "CONFERENCE ROOM 2B" },
        { type: "desk", x: 80, y: 120, w: 175, h: 92, text: "CLIENT TABLE", solid: true },
        { type: "boxes", x: 92, y: 315, w: 175, h: 92, text: "REPLACEMENT GEAR", solid: true },
        { type: "build", x: 680, y: 135, w: 180, h: 155, text: "FAILED DISPLAY", solid: true },
        { type: "floor-note", x: 390, y: 380, w: 210, h: 30, text: "CABLES LABELED: MOSTLY" },
      ],
    },
    universitySurvey: {
      name: "Campus Classroom Access",
      kicker: "University City, Philadelphia",
      playerStart: { x: 120, y: 430 },
      decor: [
        { type: "label", x: 45, y: 36, w: 270, h: 38, text: "CAMPUS CLASSROOM ACCESS" },
        { type: "desk", x: 82, y: 112, w: 190, h: 92, text: "FACILITIES DESK", solid: true },
        { type: "elevator", x: 735, y: 90, w: 155, h: 185, text: "FREIGHT ELEVATOR", solid: true },
        { type: "build", x: 645, y: 350, w: 225, h: 88, text: "DISPLAY WALL", solid: true },
        { type: "floor-note", x: 390, y: 235, w: 175, h: 32, text: "TIGHT HALLWAY TURN" },
        { type: "floor-note", x: 385, y: 390, w: 190, h: 30, text: "SALES SKETCH: ONE ARROW" },
      ],
    },
    southPhillyCommissioning: {
      name: "Training Room 3B",
      kicker: "South Philadelphia",
      playerStart: { x: 120, y: 430 },
      decor: [
        { type: "label", x: 45, y: 36, w: 245, h: 38, text: "TRAINING ROOM 3B" },
        { type: "desk", x: 78, y: 110, w: 185, h: 92, text: "CLIENT TABLE", solid: true },
        { type: "counter", x: 665, y: 325, w: 205, h: 105, text: "AV CREDENZA", solid: true },
        { type: "build", x: 390, y: 105, w: 185, h: 82, text: "CEILING SPEAKER ZONE" },
        { type: "floor-note", x: 430, y: 250, w: 185, h: 30, text: "TEST TONE: 2 OF 3" },
        { type: "floor-note", x: 300, y: 395, w: 230, h: 30, text: "CLOSEOUT DRAWING / ROOM 3A?" },
        { type: "floor-note", x: 690, y: 465, w: 170, h: 30, text: "TICKET STATUS: CLOSED" },
      ],
    },
    navyYardAccess: {
      name: "Secure Loading Dock",
      kicker: "Navy Yard, Philadelphia",
      playerStart: { x: 120, y: 430 },
      decor: [
        { type: "label", x: 45, y: 36, w: 250, h: 38, text: "NAVY YARD SECURE ACCESS" },
        { type: "desk", x: 78, y: 112, w: 185, h: 92, text: "SECURITY BOOTH", solid: true },
        { type: "elevator", x: 735, y: 90, w: 155, h: 185, text: "LOADING DOCK", solid: true },
        { type: "build", x: 630, y: 345, w: 225, h: 88, text: "TELECOM ROOM", solid: true },
        { type: "floor-note", x: 360, y: 240, w: 190, h: 32, text: "BUILDING 12 / 13?" },
        { type: "floor-note", x: 410, y: 390, w: 210, h: 30, text: "ESCORT REQUIRED" },
        { type: "floor-note", x: 685, y: 465, w: 175, h: 30, text: "ETA: STILL OPTIMISTIC" },
      ],
    },
    warrantyReturn: {
      name: "Callback Room",
      kicker: "Warranty Return Visit",
      playerStart: { x: 120, y: 430 },
      decor: [
        { type: "label", x: 45, y: 36, w: 230, h: 38, text: "CALLBACK / WARRANTY RETURN" },
        { type: "desk", x: 78, y: 110, w: 185, h: 92, text: "CLIENT TABLE", solid: true },
        { type: "counter", x: 665, y: 325, w: 205, h: 105, text: "AV CREDENZA", solid: true },
        { type: "build", x: 390, y: 105, w: 185, h: 82, text: "SYSTEM OUTPUT" },
        { type: "floor-note", x: 430, y: 250, w: 185, h: 30, text: "TESTED GOOD?" },
        { type: "floor-note", x: 300, y: 395, w: 235, h: 30, text: "PREVIOUS CLOSEOUT NOTE: BRIEF" },
        { type: "floor-note", x: 690, y: 465, w: 170, h: 30, text: "WARRANTY HOURS: WATCHED" },
      ],
    },
    executiveHandoff: {
      name: "Executive Boardroom",
      kicker: "Client Handoff",
      playerStart: { x: 120, y: 430 },
      decor: [
        { type: "label", x: 45, y: 36, w: 230, h: 38, text: "EXECUTIVE BOARDROOM" },
        { type: "desk", x: 78, y: 110, w: 185, h: 92, text: "CLIENT TABLE", solid: true },
        { type: "counter", x: 665, y: 325, w: 205, h: 105, text: "CREDENZA / LAPTOP", solid: true },
        { type: "build", x: 650, y: 110, w: 205, h: 110, text: "DISPLAY WALL", solid: true },
        { type: "floor-note", x: 410, y: 245, w: 210, h: 30, text: "TOUCH PANEL: PRESENT" },
        { type: "floor-note", x: 315, y: 390, w: 250, h: 30, text: "CHEAT SHEET: NOT PROVIDED" },
        { type: "floor-note", x: 690, y: 465, w: 175, h: 30, text: "MEETING IN 22 MIN" },
      ],
    },
  },
};
